@startuml
!include <c4/C4_Context>
!include <c4/C4_Container>
!include <c4/C4_Component>
!include <c4/C4_Deployment>
!include <c4/C4_Dynamic>

System_Boundary(c1, "Представительские расходы") {

  Container(c2, "Конфигурация 1С", "1С:Предприятие 8", "Доработка конфигурации Демонстрационное приложение (1.0.39.2) для учета представительских расходов") {
    Component(c3, "Справочник Мероприятия", "Справочник 1С", "Хранит информацию о мероприятиях")
    Component(c4, "Справочник СтатьиПредставительскихРасходов", "Справочник 1С", "Хранит информацию о статьях расходов")
    Component(c5, "Документ ПредставительскиеРасходы", "Документ 1С", "Регистрирует представительские расходы")
    Component(c6, "Регистр накопления РасходыПоМероприятиям", "Регистр 1С", "Накапливает информацию о расходах по мероприятиям")
    Component(c7, "Отчет АнализПредставительскихРасходов", "Отчет 1С", "Предоставляет аналитическую информацию о расходах")
  }

  ContainerDb(c8, "База данных 1С", "MS SQL Server/PostgreSQL", "Хранилище данных конфигурации")
  Container_Ext(c9, "RabbitMQ", "Message Queue", "Обеспечивает асинхронный обмен сообщениями")
  Container_Ext(c10, "1С:Бухгалтерия", "1С:Предприятие 8", "Бухгалтерский учет")

  Rel(c3, c8, "Сохраняет/читает данные", "ODBC")
  Rel(c4, c8, "Сохраняет/читает данные", "ODBC")
  Rel(c5, c8, "Сохраняет/читает данные", "ODBC")
  Rel(c6, c8, "Сохраняет/читает данные", "ODBC")
  Rel(c7, c8, "Читает данные", "ODBC")

  Rel(c5, c3, "Использует", "Ссылка")
  Rel(c5, c4, "Использует", "Ссылка")
  Rel(c5, c6, "Записывает", "Движения")
  Rel(c7, c6, "Читает", "Запросы")

  Rel(c6, c9, "Публикует данные о расходах", "RabbitMQ")
  Rel(c9, c10, "Получает данные о расходах", "RabbitMQ")

}

' Optional: add legends
SHOW_LEGEND()

@enduml